server:
  port: 9995
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8098/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: credit_card
          uri: lb://credit_card
          predicates:
            - Path=/creditcard/**
          filters:
            - StripPrefix=1
