server:
  port: 8086
spring:
  data:
    mongodb:
      database: credit
      host: localhost
      port: 27017
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8098/eureka/