server:
  port: 8087
spring:
  data:
    mongodb:
      database: creditcard
      host: localhost
      port: 27017
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8098/eureka/