server:
  port: 8082
spring:
  data:
    mongodb:
      database: movementAccount
      host: localhost
      port: 27017
url:
  bank:
    account: http://localhost:8083/account
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8098/eureka/